%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/weiwu/Cloud/MC3E/LiquidCases/2011_05_20_12_54_03_v2.mc3e
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/02/18 17:27:14

%% Initialize variables.
filename = '2011_04_27_07_51_41_v2 mc3e.txt';
delimiter = ' ';
startRow = 63;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
%   column11: text (%s)
%	column12: text (%s)
%   column13: text (%s)
%	column14: text (%s)
%   column15: text (%s)
%	column16: text (%s)
%   column17: text (%s)
%	column18: text (%s)
%   column19: text (%s)
%	column20: text (%s)
%   column21: text (%s)
%	column22: text (%s)
%   column23: text (%s)
%	column24: text (%s)
%   column25: text (%s)
%	column26: text (%s)
%   column27: text (%s)
%	column28: text (%s)
%   column29: text (%s)
%	column30: text (%s)
%   column31: text (%s)
%	column32: text (%s)
%   column33: text (%s)
%	column34: text (%s)
%   column35: text (%s)
%	column36: text (%s)
%   column37: text (%s)
%	column38: text (%s)
%   column39: text (%s)
%	column40: text (%s)
%   column41: text (%s)
%	column42: text (%s)
%   column43: text (%s)
%	column44: text (%s)
%   column45: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
Air_Temp = dataArray{:, 2};
MachNo_N = dataArray{:, 3};
IAS = dataArray{:, 4};
TAS = dataArray{:, 5};
Press_Alt = dataArray{:, 6};
Pot_Temp_T1 = dataArray{:, 7};
Pitot_Wing = dataArray{:, 8};
CABIN_PRES = dataArray{:, 9};
STATIC_PR = dataArray{:, 10};
DEWPT = dataArray{:, 11};
MixingRatio = dataArray{:, 12};
DewPoint = dataArray{:, 13};
FrostPoint = dataArray{:, 14};
POS_Roll = dataArray{:, 15};
POS_Pitch = dataArray{:, 16};
POS_Head = dataArray{:, 17};
POSZ_Acc = dataArray{:, 18};
POS_Lat = dataArray{:, 19};
POS_Lon = dataArray{:, 20};
POS_Alt = dataArray{:, 21};
POS_Spd = dataArray{:, 22};
POS_Trk = dataArray{:, 23};
Alpha = dataArray{:, 24};
Beta = dataArray{:, 25};
VERT_VEL = dataArray{:, 26};
Wind_Z = dataArray{:, 27};
Wind_M = dataArray{:, 28};
Wind_D = dataArray{:, 29};
TURB = dataArray{:, 30};
King_LWC_ad = dataArray{:, 31};
Nev_TWC = dataArray{:, 32};
Nev_LWCcor = dataArray{:, 33};
CDP_Conc = dataArray{:, 34};
CDP_LWC = dataArray{:, 35};
CDP_MenD = dataArray{:, 36};
CDP_VolDia = dataArray{:, 37};
CDP_EffRad = dataArray{:, 38};
DC_Conc = dataArray{:, 39};
DC_MenD = dataArray{:, 40};
DC_VolDia = dataArray{:, 41};
DC_EffRad = dataArray{:, 42};
IceMSOFreq = dataArray{:, 43};
CPCConc = dataArray{:, 44};
TSG_Date = dataArray{:, 45};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;